billing:
    resource:
        path: ../src/BikeRides/Billing/Ui/Http/
        namespace: App\BikeRides\Billing\Ui\Http
    type: attribute

rides:
    resource:
        path: ../src/BikeRides/Rides/Ui/Http/
        namespace: App\BikeRides\Rides\Ui\Http
    type: attribute
