billing:
    resource:
        path: ../src/BikeRides/Billing/UserInterface/Http/
        namespace: App\BikeRides\Billing\UserInterface\Http
    type: attribute

rides:
    resource:
        path: ../src/BikeRides/Rides/UserInterface/Http/
        namespace: App\BikeRides\Rides\UserInterface\Http
    type: attribute
