services:
  bikes-api:
    image: ghcr.io/tomcant/bike-rides:0.0.1
    build: .
    depends_on:
      - bikes-db
    ports:
      - '8080:8000'
    volumes:
      - ../apps/bikes:/var/task:rw,cached
      - ../apps/bikes/var/log:/tmp/log
      - ../packages:/var/packages:rw,cached
      - ~/.ssh:/root/.ssh:ro,delegated
      - ../reports:/var/reports:rw,delegated
    env_file: .env.dev.bikes

  bikes-db:
    image: postgres:15.2-alpine
    ports:
      - '54320:5432'
    volumes:
      - bikes-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  rides-api:
    image: ghcr.io/tomcant/bike-rides:0.0.1
    build: .
    depends_on:
      - rides-db
    ports:
      - '8081:8000'
    volumes:
      - ../apps/rides:/var/task:rw,cached
      - ../apps/rides/var/log:/tmp/log
      - ../packages:/var/packages:rw,cached
      - ~/.ssh:/root/.ssh:ro,delegated
      - ../reports:/var/reports:rw,delegated
    env_file: .env.dev.rides

  rides-db:
    image: postgres:15.2-alpine
    ports:
      - '54321:5432'
    volumes:
      - rides-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  billing-api:
    image: ghcr.io/tomcant/bike-rides:0.0.1
    build: .
    depends_on:
      - billing-db
    ports:
      - '8082:8000'
    volumes:
      - ../apps/billing:/var/task:rw,cached
      - ../apps/billing/var/log:/tmp/log
      - ../packages:/var/packages:rw,cached
      - ~/.ssh:/root/.ssh:ro,delegated
      - ../reports:/var/reports:rw,delegated
    env_file: .env.dev.billing

  billing-db:
    image: postgres:15.2-alpine
    ports:
      - '54322:5432'
    volumes:
      - billing-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  bikes-db:
    driver: local
  rides-db:
    driver: local
  billing-db:
    driver: local
