version: '3.9'

services:
  app:
    image: ghcr.io/tomcant/bike-rides:0.0.1
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8000'
    volumes:
      - ../app:/var/task:rw,cached
      - ../app/var/log:/tmp/log
      - ~/.ssh:/root/.ssh:ro,delegated
      - ../reports:/var/reports:rw,delegated
    env_file: .env.dev

  app-concurrency-instance:
    image: ghcr.io/tomcant/bike-rides:0.0.1
    build: .
    depends_on:
      - postgres
    ports:
      - '8081:8000'
    volumes:
      - ../app:/var/task:rw,cached
      - ../app/var/log:/tmp/log
      - ~/.ssh:/root/.ssh:ro,delegated
      - ../reports:/var/reports:rw,delegated
    env_file: .env.dev

  postgres:
    image: docker.io/postgres:15.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres:
    driver: local
