# Using arm64 because this image is used to run the domain
# event outbox worker on an AL2023 ARM architecture in EC2.
FROM bref/arm-php-84-console:2.3.14

COPY . $LAMBDA_TASK_ROOT

ENV LOAD_BREF_SSM_SECRETS=1

ENTRYPOINT ["bin/console"]
