services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Framework/Kernel.php'

    App\BikeRides\Bikes\UserInterface\Http\:
        resource: '../src/BikeRides/Bikes/UserInterface/Http/'
        tags:
            - 'controller.service_arguments'

    BikeRides\Foundation\Application\Command\CommandBus: '@App\Framework\Messenger\Bus\SymfonyCommandBus'
    BikeRides\Foundation\Domain\DomainEventBus: '@App\Framework\Messenger\Bus\SymfonyDomainEventBus'
    BikeRides\Foundation\Domain\TransactionBoundary: '@App\Framework\Doctrine\DbalTransactionBoundary'

    _instanceof:
        BikeRides\Foundation\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
