parameters:
    env(BIKES_API_URL): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $listBikesApiUrl: '%env(trim-trailing-slash:BIKES_API_URL)%/bike'
            $getBikeApiUrlTemplate: '%env(trim-trailing-slash:BIKES_API_URL)%/bike/{bikeId}'
            $trackingApiUrlTemplate: '%env(trim-trailing-slash:BIKES_API_URL)%/tracking?bike_id={bikeId}&from={from}&to={to}'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Framework/Kernel.php'

    App\BikeRides\Rides\UserInterface\Http\:
        resource: '../src/BikeRides/Rides/UserInterface/Http/'
        tags:
            - 'controller.service_arguments'

    BikeRides\Foundation\Application\Command\CommandBus: '@App\Framework\Messenger\Bus\SymfonyCommandBus'
    BikeRides\Foundation\Domain\AggregateEventsBus: '@App\Framework\Messenger\Bus\SymfonyAggregateEventsBus'
    BikeRides\Foundation\Domain\DomainEventBus: '@App\Framework\Messenger\Bus\SymfonyDomainEventBus'
    BikeRides\Foundation\Domain\TransactionBoundary: '@App\Framework\Doctrine\DbalTransactionBoundary'

    App\BikeRides\Rides\Domain\Model\Ride\RideRepository:
        arguments:
            $eventStore: '@App\BikeRides\Rides\Infrastructure\PostgresEventStore'

    App\BikeRides\Rides\Infrastructure\PostgresEventStore:
        arguments:
            $aggregateEventFactory: '@App\BikeRides\Rides\Domain\Model\Ride\Event\RideEventFactory'
            $dbTableName: 'rides.event_store'

    _instanceof:
        BikeRides\Foundation\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        BikeRides\Foundation\Domain\AggregateEventsSubscriber:
            tags:
                - { name: messenger.message_handler, bus: aggregate_events.bus }

        BikeRides\Foundation\Domain\DomainEventSubscriber:
            tags:
                - { name: messenger.message_handler, bus: domain_event.bus }

when@test:
    services:
        App\Tests\BikeRides\Rides\Doubles\BikeLocationFetcherStub: ~
        App\BikeRides\Rides\Application\Command\RefreshBikeLocation\BikeLocationFetcher: '@App\Tests\BikeRides\Rides\Doubles\BikeLocationFetcherStub'

        App\Tests\BikeRides\Rides\Doubles\RouteFetcherStub: ~
        App\BikeRides\Rides\Application\Command\SummariseRide\RouteFetcher: '@App\Tests\BikeRides\Rides\Doubles\RouteFetcherStub'
