framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
            aggregate_events.bus:
                default_middleware: allow_no_handlers
            domain_event.bus:
              default_middleware: allow_no_handlers
        transports:
            sync: 'sync://'
        routing:
